apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DonutL0rd/talosHomelab.git
    targetRevision: HEAD
    path: apps/demo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# You can add more applications below using the "---" separator
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: another-app
# ...
